### ISSUE TITLE
Integrate with ebay official auth module

### ISSUE THREAD

**Issue by pajaydev** [pajaydev/ebay-node-api#93]
use the below library to generate the access token.

https://github.com/eBay/ebay-oauth-nodejs-client

**Comment by TotallyNotChase** [comment]
Right, will we be just importing that library or should we copy the code from there to here? I think making this api standalone without the need of another ebay oauth package would be a good idea. As I mentioned in #10 I'm working on implementing this right now.

**Comment by pajaydev** [comment]
@TotallyNotChase  am okay with it but I thought we need sync this library with [this one](https://github.com/eBay/ebay-oauth-nodejs-client). Free feel to take this up. Kindly let me know if you need any help. 

Thanks. I appreciate it.

**Comment by TotallyNotChase** [comment]
@pajaydev yep working on it right now. What exactly do you mean by *sync* btw?

**Comment by TotallyNotChase** [comment]
@pajaydev quick update, I deployed the changes [here](https://github.com/TotallyNotChase/ebay-node-api/tree/oauth). I'd appreciate it if you could take a look and let me know if you're ok with these. I'll do a bit more bugtesting as soon as I get a chance and PR if you're ok with it.

**Comment by TotallyNotChase** [comment]
Hello again, did you get a chance to review the oauth branch?

I'm writing this to inform you that some bad weather has wrecked my
internet connectivity and hence I wasn't able to make a PR for the full
oauth flow yet. But rest assured, I'll be making one as soon as my comms
are fixed.

I also noticed you rolled out a new version and made sure to apply those
changes to my oauth branch. Although I couldn't push them up due to my
internet.

If there's anything you'd like me to know, or do in the oauth branch,
before making a PR to the main repo (once I am able to), let me know.
